Magicodes.Shop/Controllers/Settings/Settings_SmsTemplateController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using Magicodes.WeiChat.Infrastructure.MvcExtension.Ajax;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;
using Magicodes.WeiChat.Infrastructure.MvcExtension.Filters;
using Magicodes.WeiChat.Data;
using Magicodes.WeiChat.Data.Models.Settings;
using Magicodes.Shop.Controllers;
using Magicodes.WeiChat.Infrastructure.Services;
using Magicodes.WeiChat.Infrastructure;
using Magicodes.Mvc.RoleMenuFilter;
using Magicodes.Mvc.AuditFilter;

namespace Magicodes.Shop.Controllers.Settings
{
    public class Settings_SmsTemplateController : TenantBaseController<Settings_SmsTemplate>
    {
        [RoleMenuFilter("阿里短信模板设置", "A1384D4D-1BE4-48AB-8A23-4E8FE33D0FC5", "Admin,TenantManager,ShopManager",
            url: "/Settings_SmsTemplate", parentId: "72A9DBB1-4982-407E-9A78-31DEB153AB24")]
        // GET: Settings_SmsTemplate
        [AuditFilter("阿里短信模板设置页","82742d28-7ec7-444c-a8ea-36dc0740b27a")]
        public async Task<ActionResult> Index(string q, int pageIndex = 1, int pageSize = 10)
        {
            var queryable = db.Settings_SmsTemplates.Include(s => s.CreateUser).Include(s => s.UpdateUser).AsQueryable();
			if (!string.IsNullOrWhiteSpace(q))
            {
				//请替换为相应的搜索逻辑
				                queryable = queryable.Where(p => p.TemplateCode.Contains(q)|| p.SignName.Contains(q)|| p.Content.Contains(q)|| p.Demo.Contains(q)|| p.Remark.Contains(q));
				            }
			var pagedList = new PagedList<Settings_SmsTemplate>(
							 await queryable.OrderBy(p => p.Id)
							 .Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync(),
							 pageIndex, pageSize, queryable.Count());
            return View(pagedList);
        }

        // GET: Settings_SmsTemplate/Details/5
		[AuditFilter("阿里短信模板详情页","eb4af3ce-40ac-4a13-bfca-def50dc49321")]
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Settings_SmsTemplate settings_SmsTemplate = await db.Settings_SmsTemplates.FindAsync(id);
            if (settings_SmsTemplate == null)
            {
                return HttpNotFound();
            }
            return View(settings_SmsTemplate);
        }

        // GET: Settings_SmsTemplate/Create
		[AuditFilter("阿里短信模板详情创建页","8c687481-f8c9-426b-9197-307eba87758b")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Settings_SmsTemplate/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
		[AuditFilter("阿里短信模板创建","bb8e3158-100e-4439-bf55-a5fb03898df0")]
        public async Task<ActionResult> Create([Bind(Include = "Id,TemplateCode,SignName,Content,Demo,SmsType,Remark,CreateTime,CreateBy,UpdateTime,UpdateBy,TenantId")] Settings_SmsTemplate settings_SmsTemplate)
        {
            if (ModelState.IsValid)
            {
                var checkVal = db.Settings_SmsTemplates.Where(p => p.SmsType == settings_SmsTemplate.SmsType).FirstOrDefault();
                if (checkVal == null)
                {
                    settings_SmsTemplate.Id = Guid.NewGuid();
                    SetModelWithChangeStates(settings_SmsTemplate, default(Guid?));
                    db.Settings_SmsTemplates.Add(settings_SmsTemplate);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                else
                    ModelState.AddModelError("", "已经存在相同业务的短信模板!");
            }
            return View(settings_SmsTemplate);
        }
         
        // GET: Settings_SmsTemplate/Delete/5
		[AuditFilter("阿里短信模板删除页","222b3fb8-8114-48ed-9cc3-c13ca559b403")]
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Settings_SmsTemplate settings_SmsTemplate = await db.Settings_SmsTemplates.FindAsync(id);
            if (settings_SmsTemplate == null)
            {
                return HttpNotFound();
            }
            return View(settings_SmsTemplate);
        }

        // POST: Settings_SmsTemplate/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
		[AuditFilter("阿里短信模板删除功能","c87417fa-8c5f-4e2f-8024-4cf76b329fac")]
        public async Task<ActionResult> DeleteConfirmed(Guid? id)
        {
            Settings_SmsTemplate settings_SmsTemplate = await db.Settings_SmsTemplates.FindAsync(id);
            db.Settings_SmsTemplates.Remove(settings_SmsTemplate);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

		// POST: Settings_SmsTemplate/BatchOperation/{operation}
        /// <summary>
        /// 批量操作
        /// </summary>
        /// <param name="operation">操作方法</param>
        /// <param name="ids">主键集合</param>
        /// <returns></returns>
        [HttpPost]
        [Route("Settings_SmsTemplate/BatchOperation/{operation}")]
		[AuditFilter("批量删除阿里短信模板","e541408b-6bd9-4bf6-b94d-75bba8c4f8ba")]
        public async Task<ActionResult> BatchOperation(string operation, params Guid?[] ids)
        {
            var ajaxResponse = new AjaxResponse();
            if (ids.Length > 0)
            {
                try
                {
                    var models = await db.Settings_SmsTemplates.Where(p => ids.Contains(p.Id)).ToListAsync();
                    if (models.Count == 0)
                    {
                        ajaxResponse.Success = false;
                        ajaxResponse.Message = "没有找到匹配的项，项已被删除或不存在！";
                        return Json(ajaxResponse);
                    }
                    switch (operation.ToUpper())
                    {
                        case "DELETE":
                            #region 删除
                            {
                                db.Settings_SmsTemplates.RemoveRange(models);
                                await db.SaveChangesAsync();
                                ajaxResponse.Success = true;
                                ajaxResponse.Message = string.Format("已成功操作{0}项！", models.Count);
                                break;
                            }
                            #endregion
                        default:
                            break;
                    }
                }
                catch (Exception ex)
                {
                    ajaxResponse.Success = false;
                    ajaxResponse.Message = ex.Message;
                }
            }
            else
            {
                ajaxResponse.Success = false;
                ajaxResponse.Message = "请至少选择一项！";
            }
            return Json(ajaxResponse);
        }

        // GET: Settings_SmsTemplate/Demo/
        [AuditFilter("阿里短信模板预览页", "0CBD12B5-345F-41E1-B513-013430B9453C")]
        public async Task<ActionResult> Demo(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Settings_SmsTemplate settings_SmsTemplate = await db.Settings_SmsTemplates.FindAsync(id);
            if (settings_SmsTemplate == null)
            {
                return HttpNotFound();
            }
            return View(settings_SmsTemplate);
        }

        // GET: Settings_SmsTemplate/Create
        [AuditFilter("阿里短信模板详情创建页", "8c687481-f8c9-426b-9197-307eba87758b")]
        public ActionResult TestMsg()
        {
            return View();
        }

        [AuditFilter("阿里短信接口测试", "809C6345-4FE4-4C8F-A6C0-84A5EBFD04D8")]
        [HttpPost]
        public ActionResult TestMsg(string phoneNumber)
        {           
            var ajaxResponse = new AjaxResponse();
            try
            {
                var aliMsg =
                    db.Settings_AliMsgs.FirstOrDefault(p => p.TenantId == WeiChatApplicationContext.Current.TenantId);
                if (aliMsg == null)
                    throw new Exception("未对短信接口进行配置!");
                log.Log(Magicodes.Logger.LoggerLevels.Debug, "开始调用测试短信服务");
                ShopSmsService smsServer = new ShopSmsService();
                smsServer.SendTestMsg(phoneNumber);
                
                log.Log(Magicodes.Logger.LoggerLevels.Debug, "调用测试短信服务完毕");
                ajaxResponse.Success = true;
                ajaxResponse.Message = "测试完毕";           
            }
            catch (Exception ea)
            {
                ajaxResponse.Success = false;
                ajaxResponse.Message = "测试失败!原因:" + ea.Message;               
            }
            return Json(ajaxResponse);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Magicodes.Shop/Views/Settings_SmsTemplate/Create.cshtml
@model Magicodes.WeiChat.Data.Models.Settings.Settings_SmsTemplate

@{
    ViewBag.Title = "阿里短信模板创建";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>@ViewBag.Title</h2>
        <ol class="breadcrumb">
            <li>
                <a href="/">主页</a>
            </li>
            <li>
                <a href="@Url.Action("Index")">阿里短信模板设置</a>
            </li>
            <li class="active">
                <strong>@ViewBag.Title</strong>
            </li>
        </ol>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <hr style="margin: 2px 2px 10px 2px;" />
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.TemplateCode, htmlAttributes: new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.TemplateCode, new { htmlAttributes = new { @class = "form-control" } })
                                    <span class="help-block m-b-none">在阿里大于管理中心维护好短信模板后将对应的模板id拷贝到当前字段值上</span>
                                    @Html.ValidationMessageFor(model => model.TemplateCode, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.SignName, htmlAttributes: new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.SignName, new { htmlAttributes = new { @class = "form-control" } })
                                    <span class="help-block m-b-none">签名详细规范参考: http://tb.cn/OKCGyWx </span>
                                    @Html.ValidationMessageFor(model => model.SignName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                                    <span class="help-block m-b-none">变量格式:${name};示例:尊敬的${name},您的快递已在飞奔的路上，请留意查收。</span>
                                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.SmsType, htmlAttributes: new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EnumDropDownListFor(model => model.SmsType, htmlAttributes: new { @class = "form-control" })
                                    <span class="help-block m-b-none">短信对应的业务类型,每一项业务只能设置一条短信模板</span>
                                    @Html.ValidationMessageFor(model => model.SmsType, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Remark, htmlAttributes: new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.Remark, new { htmlAttributes = new { @class = "form-control" } })
                                    @*<span class="help-block m-b-none">辅助性描述文字。</span>*@
                                    @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i>&nbsp;提交</button>
                                    <a href="@Url.Action("Index")" class="btn btn-primary"><i class="fa fa-mail-reply"></i>&nbsp;返回</a>
                                </div>
                            </div>

                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    @*请自行移除没用到的样式*@
    @*复选框样式*@
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
    @*日期控件样式*@
    @Styles.Render("~/plugins/dataPickerStyles")
}

Magicodes.Shop/Views/Settings_SmsTemplate/Delete.cshtml
@using Magicodes.WeiChat.Unity;
@model Magicodes.WeiChat.Data.Models.Settings.Settings_SmsTemplate

@{
    ViewBag.Title = "删除";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>@ViewBag.Title</h2>
        <ol class="breadcrumb">
            <li>
                <a href="/">主页</a>
            </li>
            <li>
                <a href="@Url.Action("Index")">上级页面</a>
            </li>
            <li class="active">
                <strong>@ViewBag.Title</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <hr style="margin: 2px 2px 10px 2px;" />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.TemplateCode)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.TemplateCode)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.SignName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.SignName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Content)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Content)
                        </dd>

                        <dt>
                           短信类型
                        </dt>

                        <dd>
                            @(Model.SmsType.GetEnumMemberDisplayName())
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Remark)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Remark)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.CreateTime)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CreateTime)
                        </dd>
         
                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <button type="button" class="btn btn-warning pull-right" id="btnDelete"><i class="fa fa-remove"></i>&nbsp;&nbsp;删除</button>
                            <br />
                            @Html.ActionLink("返回", "Index")
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
}
@section Scripts {
    @Scripts.Render("~/plugins/iCheck")
    <script type="text/javascript">
        $(function() {
            $("input[type=checkbox]")
                .iCheck({
                    checkboxClass: 'icheckbox_square-green',
                    radioClass: 'iradio_square-green',
                });
            $('#btnDelete')
                .on('click',
                    function() {
                        mwc.message.confirm("确定要删除么？",
                            "警告",
                            function(result) {
                                if (result) {
                                    mwc.ui.setBusy();
                                    $('form').submit();
                                }
                            });
                    });
        });
    </script>
}

Magicodes.Shop/Views/Settings_SmsTemplate/Demo.cshtml
 @using System.Text.RegularExpressions
 @model Magicodes.WeiChat.Data.Models.Settings.Settings_SmsTemplate
@{
    ViewBag.Title = "模板预览";
    Layout = "~/Views/Shared/_LightLayout.cshtml";
    var content = Model.Content.Replace("\n", "<br>");
    var rm = Regex.Matches(content, @"\{\{(.+?)\}\}");
    if ((rm != null) && (rm.Count > 0))
    {
        foreach (Match item in rm)
        {
            content = content.Replace(item.Value, string.Format("<a href=\"#\" id=\"{0}\" class=\"x-editable\" data-type=\"text\" data-pk=\"1\" data-title=\"请输入内容\" data-placeholder=\"{1}\" data-value=\"\"></a>&nbsp;&nbsp;<a data-color=\"#173177\" id=\"{0}_COLOR\" class=\"colorpicker \" style=\"color:#173177\" href=\"#\">#173177</a>", item.Value.Trim('{').Trim('}'), item.Value));
        }
    }
}

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
                <hr style="margin: 2px 2px 10px 2px;" />
                <h3>请编辑下面划线的文字：</h3>
                <div class="well">
                    @Html.Raw(content)
                    <hr />
                    链接：<a href="#" id="url" class="x-editable" data-pk="1" data-title="请输入链接" data-placeholder="请输入链接" data-value="http://weichat.chinacloudsites.cn/"></a><br />
                    接收人：<a href="#" id="ReceiverId" data-pk="1" data-title="请输入内容" data-placeholder="请选择用户" data-value=""></a>
                    <p class="pull-right">
                        <button type="button" id="btnSend" class="btn btn-primary"><i class="fa fa-save"></i>&nbsp;发送</button>
                    </p>
                </div>

                <h3>消息示例：</h3>
                <div class="well">
                    @Html.Raw(Model.Demo.Replace("\n", "<br>"))
                </div>
                @Html.HiddenFor(model => model.TemplateNo)
            </div>
        </div>
    </div>
</div>

Magicodes.Shop/Views/Settings_SmsTemplate/Details.cshtml
@using Webdiyer.WebControls.Mvc;
@using Magicodes.WeiChat.Unity;

@model Magicodes.WeiChat.Data.Models.Settings.Settings_SmsTemplate

@{
    ViewBag.Title = "查看";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>@ViewBag.Title</h2>
        <ol class="breadcrumb">
            <li>
                <a href="/">主页</a>
            </li>
            <li>
                <a href="@Url.Action("Index")">上级页面</a>
            </li>
            <li class="active">
                <strong>@ViewBag.Title</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <hr style="margin: 2px 2px 10px 2px;" />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.TemplateCode)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.TemplateCode)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.SignName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.SignName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Content)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Content)
                        </dd>

                        <dt>
                           短信类型
                        </dt>

                        <dd>
                            @(Model.SmsType.GetEnumMemberDisplayName())
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Remark)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Remark)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.CreateTime)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CreateTime)
                        </dd>

                        @*<dt>
                                @Html.DisplayNameFor(model => model.GroupId)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.GroupId)
                            </dd>*@

                        @*<dt>
                                @Html.DisplayNameFor(model => model.AllowTest)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.AllowTest)
                            </dd>*@

                    </dl>
                    <p>                  
                        @Html.ActionLink("返回", "Index")
                    </p>
                </div>

            </div>
        </div>
    </div>
</div>
@section Styles {
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
}
@section Scripts {
    @Scripts.Render("~/plugins/iCheck")
    <script type="text/javascript">
        $(function() {
            $("input[type=checkbox]")
                .iCheck({
                    checkboxClass: 'icheckbox_square-green',
                    radioClass: 'iradio_square-green',
                });
        });
    </script>
}

Magicodes.Shop/Views/Settings_SmsTemplate/TestMsg.cshtml
@{
    ViewBag.Title = "阿里短信接口测试";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>@ViewBag.Title</h2>
        <ol class="breadcrumb">
            <li>
                <a href="/">主页</a>
            </li>
            <li class="active">
                <strong>@ViewBag.Title</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <hr style="margin: 2px 2px 10px 2px;"/>
                    @using (Html.BeginForm("TestMsg", "Settings_SmsTemplate", FormMethod.Post))
                    {
                        <div>
                            <div class="row">

                                <div class="form-horizontal">

                                    <div class="form-group">
                                        <label class="col-md-2 control-label">接收的手机号码:</label>
                                        <div class="col-sm-10">
                                            <input class="form-control text-box single-line" id="phoneNumber" name="phoneNumber" type="text" value="">
                                            <span class="field-Extend"></span>
                                        </div>
                                    </div>
                            
                                    <div class="form-group">
                                        <div class="col-md-2 control-label"></div>
                                        <div class="col-sm-10">
                                            <button type="submit" class="btn btn-primary but_submit"><i class="fa fa-save"></i>&nbsp;<strong>测试</strong></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


@section Styles {
    @Styles.Render("~/plugins/switcheryStyles")
}
@section Scripts {
    @Scripts.Render("~/plugins/switchery")
    <script>
        $(function() {
            $('input[type=checkbox]').attr('data-type', 'switch');
            mwc.bs.initFormControls();
            mwc.bs.initCheckedChange();
        });
       
        $("#but_submit")
            .on({
                click: function() {
                    var rec_num = $('.phoneNumber').val(); //手机号码                   
                    if (rec_num) {
                        $('#field-rec_num').html('手机号码不能为空!');
                        return;
                    }
                }
            });
    </script>

}